<?php
/**
 * Created by PhpStorm.
 * User: hu
 * Date: 2018/3/15
 * Time: 11:53
 */

namespace App\Services;


use Iterator;
use RecursiveIteratorIterator;
use Symfony\Component\Finder\Iterator\FilterIterator;
use Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator;

class ScandirFileIterator extends FilterIterator
{
    //满足条件的后缀名文件
    protected $ext = [
        'jpg', 'png'
    ];

    public function __construct($path)
    {
        parent::__construct(parent::__construct(new RecursiveIteratorIterator(new RecursiveDirectoryIterator($path, false))));
    }

    public function rewind()
    {
        return parent::rewind(); // TODO: Change the autogenerated stub
    }

    public function current()
    {
        $item = $this->getInnerIterator();
        if ($item->isFile() && in_array(pathinfo($item->getFilename(), PATHINFO_EXTENSION), $this->ext)) {
            return TRUE;
        }
    }

    public function accept()
    {
        // TODO: Implement accept() method.
    }
}