<?php

namespace App\Models;

use App\Observe\UserObserve;
use Illuminate\Database\Eloquent\Model;

class User extends Model
{

    public $fillable = ['name','email','password','creator_id'];

    public $timestamps = false;
    //
    public function role()
    {
        return $this->belongsTo(Role::class,'id','id');
    }

//    public static function boot()
//    {
//        parent::boot(); // TODO: Change the autogenerated stub
//        static::observe(UserObserve::class);
//    }
}
